Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -33,16 +33,18 @@ jobs:
         coverage run -m unittest discover tests
         coverage report > coverage.txt
 
-    - name: Upload coverage.txt to repo
+    - name: Push coverage.txt to repo
       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
       env:
-        GH_PAT: ${{secrets.GH_PAT}}
+        GH_PAT: ${{ secrets.GH_PAT }}
       run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
+        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
         git add coverage.txt
         git commit -m "Add coverage report [CI]" || echo "No changes"
-        git push origin main || echo "Push skipped"
+        git push origin main || echo "Push failed"
+
 
     - name: Clean previous build 
       run: |
